---
- name: Clean up lab environment by deleting resource groups
  hosts: localhost
  connection: local
  tasks:
  - name: Delete onpremrg
    azure_rm_resourcegroup:
    name: onpremrg
    force_delete_nonempty: yes
    state: absent
  - name: Delete onpremrg
    azure_rm_resourcegroup:
    name: fw-manager
    force_delete_nonempty: yes
    state: absent
  
